### PR TITLE
- Add privacy considerations section for review

### PR DESCRIPTION
**Pull request by saradickinson**
- Couple readability fixes

### CODE REVIEW

**Comment by raybellis** [comment]
I'd still rather see this without the reference to Client ID - being cited as a reference can lend weight to that document from people that don't realise we're saying it's a bad thing.

**Comment by saradickinson** [comment]
Ok - how about just reproducing the bulk of the text related to the mis-use of EDNS0 instead of reference that draft?
"A similar EDNS option is already being used on the public Internet in
   two different implementations.  One is between the [dnsmasq] resolver
   on the client side and Nominum's [Vantio_CacheServe] upstream.  It
   uses EDNS option code 65073 from the "Reserved for Local/Experimental
   Use" range to pass the client's Media Access Control (MAC) address.
   The other implementation is for Cisco's [Umbrella], aka OpenDNS,
   which encodes the client's MAC address and complete IP address.  It
   uses option codes 26946 and 20292, respectively, from the middle of
   the "Unassigned" range."

**Comment by pusateri** [comment]
This seems like it's in the weeds. I agree that we shouldn't reference Client ID. But talking about specific cases of bad usage doesn't seem to belong here either. We should simply state the behavior we do want in the spec.

**Comment by Abhayakara** [comment]
On Dec 14, 2017, at 11:50 AM, Tom Pusateri <notifications@github.com> wrote:
> This seems like it's in the weeds. I agree that we shouldn't reference Client ID. But talking about specific cases of bad usage doesn't seem to belong here either. We should simply state the behavior we do want in the spec.

It feels to me as if talking about this is just painting a target on the document.   The reality is that the document doesn't create a trackable ID, and we shouldn't worry about it.   If there is a real privacy consideration here, it's that the connection itself creates trackable state and prevents queries from coming from successive privacy addresses, as could be the case with regular DNS queries.   For that reason, applications that have the potential to compromise user privacy in this way shouldn't use long-lived DNS connections in general, whether session signaling is in use or not.

**Comment by bortzmeyer** [comment]
I tend to agree with @pusateri and @Abhayakara : a "do not do that" section is both dangerous (it may give ideas to bad people) and too limited (the number of bad ideas is unfortunately unlimited, we cannot mention all of them).

I just sent a proposed text to dnsop.

**Pull request closed without merging**
